services:
  mysql:
    image: mysql:8.0
    container_name: boxpro-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boxpro_db
      MYSQL_USER: boxpro_user
      MYSQL_PASSWORD: boxpro_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - boxpro-net

  backend:
    build:
      context: ./backend
    container_name: boxpro-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/boxpro_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      
      # JPA Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      
      # Server Configuration
      SERVER_PORT: 8080
      # REMOVIDO O CONTEXT-PATH PROBLEMÁTICO
      # SERVER_SERVLET_CONTEXT_PATH: /api
      
      # JWT Configuration
      APP_JWT_SECRET: boxProSecretKey2024SuperSecureJWTSigningKeyForHS512Algorithm2024!
      APP_JWT_EXPIRATION: 86400000
      
      # Logging
      LOGGING_LEVEL_COM_BOXPRO: DEBUG
      
    networks:
      - boxpro-net

volumes:
  mysql_data:

networks:
  boxpro-net:
    driver: bridge